DELETE http://localhost:8080/tweets/delete/e44d1604-d219-4d45-906e-eff3faa2c96b
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6ImE3NzhkMzY4LWY4OWYtNGVlZS1iZDRiLTE5NjdlMmE2MTUzNiIsIm5hbWUiOiJNYWtzaW0iLCJsb2dpbiI6InNpenp6ZXIiLCJwYXNzd29yZCI6IjMxYTU4ZTUxNzM3MjJiOTNmY2IxMmQ1YjQ3NGViNzM1IiwiY29uZmlybWVkIjpmYWxzZSwiY29uZmlybUhhc2giOiJhYzFkZDIwOWNiY2M1ZTVkMWM2ZTI4NTk4ZThjYmJlOCIsImRlc2NyaXB0aW9uIjpudWxsLCJsb2NhdGlvbiI6Ik1pbnNrLCBSdXNzaWEiLCJhdmF0YXIiOm51bGwsImJhY2tncm91bmRJbWFnZSI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyMS0xMS0wNFQwODo1Mzo1NC4yNzZaIiwidXBkYXRlZEF0IjoiMjAyMS0xMS0wNVQwODoxMDo1OC41MjNaIn0sImlhdCI6MTYzNjQ0Mzk5MCwiZXhwIjoxNjM5MDM1OTkwfQ.WKd0grosnuN4anuMrKd-bdP_XlMOuVDXLPGUU_6YFX0